/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 base.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Base(props) {
  const { nodes, materials } = useGLTF('/models/CpuCooler/base.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.basis.geometry} material={materials['Material.001']} position={[-0.068, 0.453, 0.542]} rotation={[Math.PI / 2, 0, 0]} scale={0.225} />
      <mesh geometry={nodes.defaultMaterial002.geometry} material={materials['material.003']} position={[0, 0.69, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.226} />
    </group>
  )
}

useGLTF.preload('/models/CpuCooler/base.glb')
