/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 fin.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Fin(props) {
  const { nodes, materials } = useGLTF('/models/CpuCooler/fin.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.fins001.geometry} material={materials.material_1} rotation={[-Math.PI, 0, -Math.PI]} scale={0.205} />
    </group>
  )
}

useGLTF.preload('/models/CpuCooler/fin.glb')
