/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 nvme.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Nvme(props) {
  const { nodes, materials } = useGLTF('/models/Motherboard/nvme.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_81.geometry} material={materials['Material.025']} position={[-16.8, 8.126, 21.065]} />
      <mesh geometry={nodes.Object_79.geometry} material={materials['Material.026']} position={[-16.8, 8.126, 21.065]} />
    </group>
  )
}

useGLTF.preload('/models/Motherboard/nvme.glb')
