/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 caseCube.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Case(props) {
  const { nodes, materials } = useGLTF('/models/Case/caseCube.glb')
  return (
    <group {...props} dispose={null}>
    <group position={[0.974, 3.998, -0.402]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.483, 0.918, 0.43]}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group position={[1.955, -11.55, -0.639]} scale={[1, 1.022, 1]}>
          <mesh geometry={nodes.Object_130.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_131.geometry} material={materials['Material.001']} />
        </group>
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} position={[-1.834, -10.573, -0.366]} scale={[0.131, 0.378, 0.669]} />
        <mesh geometry={nodes.Object_86.geometry} material={materials['Material.001']} position={[-1.849, -9.412, 0.376]} scale={[0.048, 0.048, 0.007]} />
        <mesh geometry={nodes.Object_88.geometry} material={materials['Material.001']} position={[-1.772, -9.648, 0.323]} scale={[0.172, 0.204, 0.018]} />
        <mesh geometry={nodes.Object_90.geometry} material={materials['Material.001']} position={[1.575, -9.631, 0.327]} rotation={[Math.PI, 0, Math.PI]} scale={[0.172, 0.204, 0.018]} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.material_0} position={[-1.872, -9.485, 0.383]} rotation={[0, 0, Math.PI]} scale={[0.023, 0.027, 0.003]} />
        <mesh geometry={nodes.Object_94.geometry} material={materials['Material.001']} position={[-1.849, -9.479, 0.366]} scale={[0.048, 0.027, 0.015]} />
        <mesh geometry={nodes.Object_96.geometry} material={materials['Material.001']} position={[-1.849, -13.705, 0.366]} scale={[0.048, 0.027, 0.015]} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.material_0} position={[-1.859, -13.691, 0.383]} rotation={[0, 0, Math.PI]} scale={[0.023, 0.027, 0.003]} />
        <mesh geometry={nodes.Object_100.geometry} material={materials.material_0} position={[1.643, -9.485, 0.383]} scale={[0.023, 0.027, 0.003]} />
        <mesh geometry={nodes.Object_102.geometry} material={materials['Material.001']} position={[1.667, -9.501, 0.366]} rotation={[0, 0, -Math.PI / 2]} scale={[0.048, 0.027, 0.015]} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.material_0} position={[-1.846, -11.381, -0.303]} rotation={[Math.PI / 2, 0, 0]} scale={[0.037, 0.042, 0.037]} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.material_0} position={[-1.846, -11.595, -0.303]} rotation={[Math.PI / 2, 0, 0]} scale={[0.037, 0.042, 0.037]} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.material_0} position={[-1.846, -11.801, -0.303]} rotation={[Math.PI / 2, 0, 0]} scale={[0.037, 0.042, 0.037]} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.material_0} position={[-1.846, -12.005, -0.303]} rotation={[Math.PI / 2, 0, 0]} scale={[0.037, 0.042, 0.037]} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.material_0} position={[-1.846, -12.167, -0.303]} rotation={[Math.PI / 2, 0, 0]} scale={[0.037, 0.042, 0.037]} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.material_0} position={[-1.846, -12.382, -0.303]} rotation={[Math.PI / 2, 0, 0]} scale={[0.037, 0.042, 0.037]} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.material_0} position={[-1.846, -12.588, -0.303]} rotation={[Math.PI / 2, 0, 0]} scale={[0.037, 0.042, 0.037]} />
        <mesh geometry={nodes.Object_104.geometry} material={materials['Material.001']} position={[1.535, -9.599, 0.342]} rotation={[Math.PI / 2, 0, 0]} scale={[0.08, 0.012, 0.08]} />
        <mesh geometry={nodes.Object_106.geometry} material={materials['Material.001']} position={[-1.753, -9.599, 0.342]} rotation={[Math.PI / 2, 0, 0]} scale={[0.08, 0.012, 0.08]} />
        <mesh geometry={nodes.Object_108.geometry} material={materials['Material.001']} position={[1.535, -13.587, 0.34]} rotation={[Math.PI / 2, 0, 0]} scale={[0.08, 0.012, 0.08]} />
        <mesh geometry={nodes.Object_110.geometry} material={materials['Material.001']} position={[-1.753, -13.587, 0.339]} rotation={[Math.PI / 2, 0, 0]} scale={[0.08, 0.012, 0.08]} />
        <mesh geometry={nodes.Object_133.geometry} material={materials.material_0} position={[1.561, -13.551, 0.483]} rotation={[Math.PI / 2, 0, 0]} scale={[0.057, 0.065, 0.057]} />
        <mesh geometry={nodes.Object_135.geometry} material={materials['Material.008']} position={[1.418, -13.859, -1.516]} scale={[0.117, 0.054, 0.117]} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} position={[-1.936, -9.704, 0.301]} rotation={[0, 0, -Math.PI / 2]} scale={0.021} />
        <mesh geometry={nodes.Object_82.geometry} material={materials['Material.002']} position={[0.008, -9.377, -0.64]} scale={[1.378, 0.782, 0.829]} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} position={[-1.956, -12.019, 0.019]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={1.086} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.001']} position={[-0.944, -13.794, -0.645]} scale={[0.988, 0.988, 1.062]} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.001']} position={[-0.935, -12.691, -1.533]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.material_0} position={[-1.319, -12.003, -1.552]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.material_0} position={[0.5, -12.173, -1.551]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.material_0} position={[0.5, -11.093, -1.551]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.material_0} position={[0.492, -10.338, -1.551]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.material_0} position={[0.946, -10.452, -1.403]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.material_0} position={[1.184, -10.452, -1.403]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.material_0} position={[1.298, -10.792, -1.403]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.material_0} position={[1.182, -11.383, -1.403]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.material_0} position={[0.941, -11.383, -1.403]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.material_0} position={[1.185, -12.292, -1.403]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.material_0} position={[0.944, -12.292, -1.403]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.material_0} position={[0.202, -12.431, -1.551]} rotation={[0, 0, -Math.PI / 2]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.material_0} position={[-0.402, -12.431, -1.551]} rotation={[0, 0, -Math.PI / 2]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.material_0} position={[-0.995, -12.431, -1.551]} rotation={[0, 0, -Math.PI / 2]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.material_0} position={[-0.807, -11.505, -1.551]} rotation={[0, 0, -0.796]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.material_0} position={[-0.276, -11.505, -1.551]} rotation={[0, 0, -0.796]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.material_0} position={[0.187, -11.57, -1.551]} rotation={[0, 0, -0.796]} scale={[0.219, 0.136, 0.129]} />
        <mesh geometry={nodes.Object_128.geometry} material={materials['Material.005']} position={[-0.026, -11.29, 0.409]} rotation={[Math.PI / 2, 0, 0]} scale={1.953} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.material_0} position={[0.694, -11.921, -1.455]} rotation={[Math.PI / 2, 0, 0.803]} scale={[0.089, 0.512, 0.512]} />
        <mesh geometry={nodes.Object_50.geometry} material={materials['Material.003']} position={[0.694, -10.889, -1.455]} rotation={[Math.PI / 2, 0, 0.803]} scale={[0.089, 0.512, 0.512]} />
        <mesh geometry={nodes.Object_54.geometry} material={materials['Material.001']} position={[-0.494, -10.603, -1.56]} rotation={[Math.PI / 2, 0, -0.01]} scale={[0.851, 0.347, 0.347]} />
        <mesh geometry={nodes.Object_76.geometry} material={materials['Material.001']} position={[-0.953, -12.841, -0.632]} scale={[0.99, 1, 1]} />
        <mesh geometry={nodes.Object_78.geometry} material={materials['Material.001']} position={[-0.087, -12.692, -1.726]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_80.geometry} material={materials['Material.001']} position={[-0.963, -9.356, -0.694]} />
        <mesh geometry={nodes.Object_84.geometry} material={materials['Material.001']} position={[1.853, -11.553, -1.706]} rotation={[Math.PI / 2, 0, 0]} scale={[0.182, 1, 2.207]} />
        <mesh geometry={nodes.Object_112.geometry} material={materials['Material.001']} position={[1.729, -11.403, -0.523]} rotation={[0, 0, -Math.PI / 2]} scale={[2.081, 1, 0.878]} />
        <mesh geometry={nodes.Object_114.geometry} material={materials.material_0} position={[0.536, -13.323, -0.471]} rotation={[0, 0, -Math.PI / 2]} scale={[0.497, 0.566, 0.566]} />
        <mesh geometry={nodes.Object_116.geometry} material={materials['Material.004']} position={[1.926, -9.476, -1.525]} scale={[1, 1.022, 1]} />
        <mesh geometry={nodes.Object_118.geometry} material={materials.material_0} position={[-0.105, -9.662, -1.533]} rotation={[Math.PI / 2, 0, 0]} scale={1.109} />
        <mesh geometry={nodes.Object_120.geometry} material={materials.material_0} position={[-1.053, -9.662, -1.533]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[-1.934, -11.612, -0.656]} rotation={[0, 0, -Math.PI / 2]} scale={1.079} />
      </group>
    </group>
  </group>
  )
}

useGLTF.preload('/models/Case/caseCube.glb')
