/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 memory.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/memory.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.048, 0, 0]} rotation={[0, 0, 3.141]} scale={0.465}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.059']} position={[-0.104, 0, -0.032]} scale={0.73} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.060']} position={[-0.104, 0, -0.032]} scale={0.73} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.053']} position={[-0.104, 0, -0.032]} scale={0.73} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.055']} position={[-0.104, 0, -0.032]} scale={0.73} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.056']} position={[-0.104, 0, -0.032]} scale={0.73} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.057']} position={[-0.104, 0, -0.032]} scale={0.73} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.058']} position={[-0.104, 0, -0.032]} scale={0.73} />
      </group>
    </group>
  )
}

useGLTF.preload('/memory.glb')
